# PDIM

PDIM (**P**oints in N **DIM**ensions) minimizes P points in N dimensions.

### Reference
If you use PDIM or dpMD, please refer to the following publication:

### FAQ
- Where can I chat with other ColabFold users?
  - See our [Discord](https://discord.gg/gna8maru7d) channel!

### FAQ
Testar **name** and **DISTINCT** name
calculate `normal modes`
```
charmm -i scripts/normal-modes.inp
```

**PDIM** is also available in a compiled version for [Linux](https://github.com/soedinglab/MMseqs2/archive/71dd32ec43e3ac4dabf111bbc4b124f1c66a85f1.zip) and Windows.


generate crd and dcd of modes:
```
charmm -i scripts/normal-modes-dcd-crd.inp nmodes=20
```

generating normal mode combination
```
bash scripts/mdenm-modes-combination.sh
```

combine normal modes
```
charmm -i scripts/generate-combined-modes.inp ncomb=6
```

**MDeNM**
```
scripts/mdenm-namd-exc.sh
```

```
scripts/mdenm-namd-md.sh
```

**VMOD**
```
scripts/runvmod-comb.sh = run vmod to obtain displaced conformations
```

**dpMD**

In this step, the equlibrated system will be driven towards all conformations generated by **VMOD**.

Initially, each conformation will be set as a target in the PDB format using `charmm`. In this example, six replicas were set in `nreps`:
```
charmm -i scripts/target.inp nreps=6
```
Following, TMD will be performed using `namd`:
```
bash scripts/tmd-namd.sh
```

```
charmm -i scripts/restraints.inp nreps=6
```

```
bash scripts/tmd-equil-namd.sh
```

```
bash scripts/tmd-free-md-namd.sh
```

